### ISSUE TITLE
Unified output of Tensor.shape and tf.Tensor.shape?

### ISSUE THREAD

**Issue by kongkong617** [Hong-Xiang/dxlearn#74]
Tensor.shape is now return a numpy like shape, equal to Tensor.data.shape.as_list().
can we unify it?

**Comment by Hong-Xiang** [comment]
Maybe we should search interfaces of other libraries like 
- [ ] PyTorch
- [ ] CNTK
- [ ] Keras (if any)

**Comment by Hong-Xiang** [comment]
A new method `shape_list` were added to `dxl.data.function`,

# requirement
dxl.data >= 0.0.15

# useage
```python
from dxl.data.function import shape_list
import numpy as np
import tensorflow as tf
t_np = np.ones([2,3])
t_tf = tf.constant(t_np)

shape_list(t_np) # [2, 3]
shape_list(t_tf) # [2, 3]


t = tf.placeholder(tf.float32, [None, 128, 128, 3])
shape_list(t) # [None, 128, 128, 3]
```
